rootProject.name = 'WellMeet-Backend'

include 'common-client'
include 'domain-common'
include 'domain-reservation'
include 'domain-member'
include 'domain-owner'
include 'domain-restaurant'
include 'api-owner'
include 'api-user'
include 'infra-redis'
include 'infra-kafka'
include 'batch-reminder'
include 'discovery-server'

