server:
  port: 8087

spring:
  application:
    name: api-owner-service

  config:
    import:
      - classpath:dev-secret.yml
      - classpath:application-infra-redis-dev.yml
      - classpath:application-infra-kafka-dev.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

cors:
  origin: ${secret.cors.origin}
