spring:
  config:
    import:
      - classpath:dev-secret.yml
      - classpath:application-domain-dev.yml
      - classpath:application-infra-redis-dev.yml
      - classpath:application-infra-kafka-dev.yml

cors:
  origin: ${secret.cors.origin}
