spring:
  config:
    import:
      - classpath:application-domain-local.yml
      - classpath:application-infra-redis-local.yml
      - classpath:application-infra-kafka-local.yml
  application:
    name: WellMeet-Backend
server:
  port: 8081

cors:
  origin: http://localhost:5173
