spring:
  config:
    import:
      - classpath:application-domain-local.yml
      - classpath:application-domain-redis-local.yml
  application:
    name: WellMeet-Backend

cors:
  origin: http://localhost:5173
