spring:
  application:
    name: api-user-service
  config:
    import:
      - classpath:application-infra-redis-test.yml
      - classpath:application-infra-kafka-test.yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    discovery:
      enabled: false

server:
  port: 8086

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

cors:
  origin: http://localhost:5173
